export const outCodes = {
    PREPARE_TO_CAMUNDA_8: "E13_PREPARE_TO_CAMUNDA_8",
    CHECK_INSTRUMENTS: "E14_CHECK_INSTRUMENTS",
    IMPROVE_PROCESS_READABILITY: "E15_IMPROVE_PROCESS_READABILITY",
    DECOMPOSE_PROCESS: "E16_DECOMPOSE_PROCESS",
    LEAVE_ALONE: "E17_LEAVE_ALONE",
}

export const inputCodes = {
    PREPARE_TO_CAMUNDA_8: "E1_PREPARE_TO_CAMUNDA_8",
    NOT_PREPARE_TO_CAMUNDA_8: "E12_NOT_PREPARE_TO_CAMUNDA_8",
    HANDLE_ERROR: "E2_HANDLE_ERROR",
    HARD_TO_FEATURES: "E3_HARD_TO_FEATURES",
    REPEATABLE_MOMENTS: "E5_REPEATABLE_MOMENTS",
    CUSTOM_TASKLIST: "E6_CUSTOM_TASKLIST",
    NO_CUSTOM_TASKLIST: "E11_NO_CUSTOM_TASKLIST",
    QUICK_RELEASE: "E10_QUICK_RELEASE",
    NOT_QUICK_RELEASE: "E7_NOT_QUICK_RELEASE",
}

export const allowStates = {
    BASE_INFO: "BASE_INFO",
    QUESTIONAIRE: "QUESTIONAIRE",
    CHECK_RESULTS: "CHECK_RESULTS"
  }

export const normilizeRecomendationStatus = {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGHT: "HIGHT"
}