export const outCodes = {
    PREPARE_TO_CAMUNDA_8: "PREPARE_TO_CAMUNDA_8",
    CHECK_INSTRUMENTS: "CHECK_INSTRUMENTS",
    IMPROVE_PROCESS_READABILITY: "IMPROVE_PROCESS_READABILITY",
    DECOMPOSE_PROCESS: "DECOMPOSE_PROCESS",
    LEAVE_ALONE: "LEAVE_ALONE",
}

export const inputCodes = {
    PREPARE_TO_CAMUNDA_8: "PREPARE_TO_CAMUNDA_8",
    NOT_PREPARE_TO_CAMUNDA_8: "NOT_PREPARE_TO_CAMUNDA_8",
    HANDLE_ERROR: "HANDLE_ERROR",
    HARD_TO_FEATURES: "HARD_TO_FEATURES",
    REPEATABLE_MOMENTS: "REPEATABLE_MOMENTS",
    CUSTOM_TASKLIST: "CUSTOM_TASKLIST",
    NO_CUSTOM_TASKLIST: "NO_CUSTOM_TASKLIST",
    QUICK_RELEASE: "QUICK_RELEASE",
    NOT_QUICK_RELEASE: "NOT_QUICK_RELEASE",
}

export const allowStates = {
    QUESTIONAIRE: "QUESTIONAIRE",
    CHECK_RESULTS: "CHECK_RESULTS"
  }