
module.exports = {
    outCodes: {
        PREPARE_TO_CAMUNDA_8: "PREPARE_TO_CAMUNDA_8",
        CHECK_INSTRUMENTS: "CHECK_INSTRUMENTS",
        IMPROVE_PROCESS_READABILITY: "IMPROVE_PROCESS_READABILITY",
        DECOMPOSE_PROCESS: "DECOMPOSE_PROCESS",
        LIVE_ALONE: "LIVE_ALONE",
    },
    inputCodes: {
        PREPARE_TO_CAMUNDA_8: "PREPARE_TO_CAMUNDA_8",
        NOT_PREPARE_TO_CAMUNDA_8: "NOT_PREPARE_TO_CAMUNDA_8",
        HANDLE_ERROR: "HANDLE_ERROR",
        TOO_HARD_TO_FEATURES: "TOO_HARD_TO_FEATURES",
        HARD_TO_FEATURES: "HARD_TO_FEATURES",
        REPEATABLE_MOMENTS: "REPEATABLE_MOMENTS",
        CUSTOM_TASKLIST: "CUSTOM_TASKLIST",
        NO_CUSTOM_TASKLIST: "NO_CUSTOM_TASKLIST",
        QUICK_RELEASE: "QUICK_RELEASE",
        NOT_QUICK_RELEASE: "NOT_QUICK_RELEASE",
        AVAILABLE_NOT_QUICK_RELEASE: "AVAILABLE_NOT_QUICK_RELEASE",
        AVAILABLE_QUICK_RELEASE: "AVAILABLE_QUICK_RELEASE",
    }
}